CREATE TABLE USERS
(
    USER_ID  BIGINT AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE     VARCHAR(5)   NOT NULL,
    PRIMARY KEY (USER_ID)
);

ALTER TABLE USERS
    ADD CONSTRAINT CHECK__ROLE
        CHECK (ROLE IN ('ADMIN', 'USER'));

ALTER TABLE USERS
    ADD CONSTRAINT UK_ORDERS__USERNAME UNIQUE (USERNAME);