CREATE TABLE USERS
(
    USER_ID   BIGINT        AUTO_INCREMENT,
    USERNAME  VARCHAR(255)  NOT NULL,
    PASSWORD  VARCHAR(255)  NOT NULL,
    PRIMARY KEY (USER_ID)
);

ALTER TABLE USERS
    ADD CONSTRAINT UK_ORDERS__USERNAME UNIQUE(USERNAME);