CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID BIGINT AUTO_INCREMENT,
    FIRST_NAME  VARCHAR(255) NOT NULL,
    LAST_NAME   VARCHAR(255) NOT NULL,
    JOB         INT          NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID)
);

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT CHECK__JOB
        CHECK (JOB IN ('WAITER', 'COOK', 'DELIVERY'));

CREATE INDEX EMPLOYEES__JOB ON EMPLOYEES (JOB);
