CREATE TABLE ORDERS
(
    ORDER_ID      BIGINT AUTO_INCREMENT,
    PRICE         DECIMAL(19, 4) NOT NULL,
    HOUR_ORDER    timestamp default sysdate,
    HOUR_AWAY     timestamp default null,
    TYPE_OF_ORDER VARCHAR(9)     NOT NULL,
    CUSTOMER_ID   BIGINT         NOT NULL,
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE ORDER_ITEMS
(
    ORDER_ITEM_ID   BIGINT,
    ORDER_ITEM_NAME VARCHAR(255)   NOT NULL,
    PRICE           DECIMAL(19, 4) NOT NULL,
    AMOUNT          INTEGER        NOT NULL,
    ORDER_ID        BIGINT,
    PRIMARY KEY (ORDER_ITEM_ID)
);

CREATE TABLE ORDERS__EMPLOYEE
(
    ORDER_ID    BIGINT,
    EMPLOYEE_ID BIGINT,
    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
    CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDER_ITEMS__ORDER_ID_TO_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);

ALTER TABLE ORDERS
    ADD CONSTRAINT CHECK__TYPE_OF_ORDER
        CHECK (TYPE_OF_ORDER IN ('ON_SITE', 'DELIVERY'));

CREATE INDEX ORDERS__HOUR_AWAY ON ORDERS (HOUR_AWAY);
CREATE INDEX ORDERS__HOUR_AWAY ON ORDERS (TYPE_OF_ORDER);

