CREATE TABLE ORDERS
(
    ORDER_ID       BIGINT     AUTO_INCREMENT,
    PRICE          INTEGER    NOT NULL,
    HOUR_ORDER     timestamp  default sysdate,
    HOUR_AWAY      timestamp  default null,
    TYPE_OF_ORDER  INT        NOT NULL,
    USER_ID        BIGINT     NOT NULL,
    PRIMARY KEY(ORDER_ID)
);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS__USER_ID_TO_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE ORDERS
    ADD CONSTRAINT CHECK__TYPE_OF_ORDER
        CHECK (TYPE_OF_ORDER IN ('ON_SITE', 'DELIVERY'));

CREATE INDEX ORDERS__HOUR_AWAY ON ORDERS(HOUR_AWAY);
CREATE INDEX ORDERS__HOUR_AWAY ON ORDERS(TYPE_OF_ORDER);

CREATE TABLE ORDERS__MENU_ITEMS
(
    ORDER_ID BIGINT,
    MENU_ITEM_ID BIGINT,
    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_MENU_ITEM_ID FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEMS(MENU_ITEM_ID)
);

CREATE TABLE ORDERS__EMPLOYEE
(
    ORDER_ID BIGINT,
    EMPLOYEE_ID BIGINT,
    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);