-- Insert sample data into MENU table
INSERT INTO MENU (MENU_NAME) VALUES ('Breakfast Menu');
INSERT INTO MENU (MENU_NAME) VALUES ('Lunch Menu');
INSERT INTO MENU (MENU_NAME) VALUES ('Dinner Menu');

-- Insert sample data into MENU_ITEMS table
INSERT INTO MENU_ITEMS (MENU_ITEM_NAME, PRICE, STATUS, MENU_ID) VALUES ('Pancakes', 5.99, 'ACTIVE', 1);
INSERT INTO MENU_ITEMS (MENU_ITEM_NAME, PRICE, STATUS, MENU_ID) VALUES ('Omelette', 7.99, 'ACTIVE', 1);
INSERT INTO MENU_ITEMS (MENU_ITEM_NAME, PRICE, STATUS, MENU_ID) VALUES ('French Toast', 6.99, 'ACTIVE', 1);

INSERT INTO MENU_ITEMS (MENU_ITEM_NAME, PRICE, STATUS, MENU_ID) VALUES ('Grilled Cheese Sandwich', 8.99, 'ACTIVE', 2);
INSERT INTO MENU_ITEMS (MENU_ITEM_NAME, PRICE, STATUS, MENU_ID) VALUES ('Caesar Salad', 10.99, 'ACTIVE', 2);
INSERT INTO MENU_ITEMS (MENU_ITEM_NAME, PRICE, STATUS, MENU_ID) VALUES ('Burger', 12.99, 'ACTIVE', 2);

INSERT INTO MENU_ITEMS (MENU_ITEM_NAME, PRICE, STATUS, MENU_ID) VALUES ('Steak', 19.99, 'ACTIVE', 3);
INSERT INTO MENU_ITEMS (MENU_ITEM_NAME, PRICE, STATUS, MENU_ID) VALUES ('Spaghetti', 14.99, 'ACTIVE', 3);
INSERT INTO MENU_ITEMS (MENU_ITEM_NAME, PRICE, STATUS, MENU_ID) VALUES ('Grilled Salmon', 17.99, 'ACTIVE', 3);
