timeToWaitForReceive: 100
multiplierTimeToCook: 5000
multiplierTimeToDelivery: 100
server:
  port: 9090
spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:./test-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1'
    username: 'sa'
    password: 'pass'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update