spring:
  h2.console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:~/IdeaProjects/Restaurant-Management-System/database/restaurant-db'
    username: 'sa'
    password: 'pass'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
