timeToWaitForReceive: 30
multiplierTimeToCook: 100
timeToDelivery: 100
spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:~/IdeaProjects/Restaurant-Management-System/database/restaurant-db'
    username: 'sa'
    password: 'pass'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate